language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r littlekingdom-aws-springboot *
  - mkdir -p deploy
  - mv littlekingdom-aws-springboot.zip deploy/littlekingdom-aws-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: littlekingdom-aws-springboot # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wingindream@gmail.com